@startuml
'https://plantuml.com/component-diagram


package "SpringBoot demo" {

  [ThumbnailGenerator] <<KafkaListener>>
  http - [PhotoService] <<SpringBootMicroService>>


    node kafka {
    [photos] <<KafkaTopic>>
    }
  database "MongoDB" {
    folder "collections" {
      [photo-album]
    }
  }

}




[PhotoService] -left-> [photo-album]
[PhotoService] -left-> [photos]
[ThumbnailGenerator] --> [photos]
[ThumbnailGenerator] --> [photo-album]
@enduml
