services:
  user-service:
    build:
      context: .
      target: user-service
    ports:
      - 8080:8080
  db:
    image: mongo:latest
    ports:
      - 27017:27017
  kafka:
    image: apache/kafka-native:latest
    ports:
      - 9092:9092
