services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
  kafka:
    image: apache/kafka-native:latest
    ports:
      - 9092:9092
    hostname: kafka
  photo-service:
    build:
      context: .
      target: photo-service
    ports:
      - 8080:8080
      - 52437:52437

