spring:
  application:
    name: ThumbnailGenerator
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: my.demo.common
    bootstrap-servers: "kafka:9092"
  data:
    mongodb:
      uri: "mongodb://db:27017/photo-album"
management.metrics.enabled.all: false
